version: 2.1

description: |
  Build and publish hybrid Apps based on Ionic for iOS / Android.
  Repository: https://github.com/okode/orbs

cache-key-gradle: &cache-key-gradle
  key: cache-gradle-{{ .Environment.CIRCLE_JOB }}-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "build.gradle" }}

orbs:
  common: okode/common@1.0.169
  node: circleci/node@4

executors:
  java-node:
    docker:
      - image: circleci/openjdk:8-node-browsers
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD

jobs:
  app:
    parameters:
      path:
        type: string
        default: app
      package:
        type: boolean
        default: false
      skip-e2e:
        type: boolean
        default: false
      base-href:
        type: string
        default: "/"
      archive-name:
        type: string
        default: ""
    executor: java-node
    working_directory: ~/project/<< parameters.path >>
    steps:
      - checkout:
          path: ~/project
      - node/install-packages
      - when:
          condition: << parameters.package >>
          steps:
            - run:
                name: Installing Ionic
                command: sudo npm install -g ionic
            - run:
                name: Building
                command: ionic build --prod -- --base-href << parameters.base-href >>
            - when:
                condition: << parameters.archive-name >>
                steps:
                  - run:
                      name: Archiving www folder
                      command: tar zcvf << parameters.archive-name >> www
                  - persist_to_workspace:
                      root: .
                      paths:
                        - << parameters.archive-name >>
            - unless:
                condition: << parameters.archive-name >>
                steps:
                  - persist_to_workspace:
                      root: .
                      paths:
                        - www
      - unless:
          condition: << parameters.package >>
          steps:
            - run:
                name: Building
                command: npm run build -- --progress false --aot
            - common/chrome-upgrade
            - run:
                name: Running unit tests
                command: npm run test -- --configuration ci
            - unless:
                condition: << parameters.skip-e2e >>
                steps:
                  - run:
                      name: Running e2e tests
                      command: npm run e2e
            - store_test_results:
                path: test-results
            - persist_to_workspace:
                root: .
                paths:
                  - node_modules
                  - test-results
                  - lint-results.json
                  - coverage
                  - www
  server:
    parameters:
      path:
        type: string
        default: server
      package:
        type: boolean
        default: false
      copy-static-resources:
        type: boolean
        default: true
      executor:
        type: executor
        default: java-node
    executor: << parameters.executor >>
    working_directory: ~/project/<< parameters.path >>
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          <<: *cache-key-gradle
      - when:
          condition: << parameters.package >>
          steps:
            - when:
                condition: << parameters.copy-static-resources >>
                steps:
                  - attach_workspace:
                      at: /tmp/workspace
                  - run:
                      name: Copying resources
                      command: mkdir -p src/main/resources/static && cp -R /tmp/workspace/www/* src/main/resources/static
            - run:
                name: Building and Packaging
                command: ./gradlew bootJar
            - persist_to_workspace:
                root: .
                paths:
                  - build/libs
      - unless:
          condition: << parameters.package >>
          steps:
            - run:
                name: Building
                command: ./gradlew build jacocoTestReport
            - store_test_results:
                path: build/test-results
            - persist_to_workspace:
                root: .
                paths:
                  - src
                  - build
      - save_cache:
          <<: *cache-key-gradle
          paths:
            - ~/.gradle
