version: 2.1

description: |
  Build and publish Angular libraries.
  Repository: https://github.com/okode/orbs

orbs:
  common: okode/common@1
  node: circleci/node@4

jobs:
  test:
    parameters:
      project:
        type: string
      skip-tests:
        type: boolean
        default: false
      skip-e2e:
        type: boolean
        default: false
    executor: common/node-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Building
          command: npm run build -- << parameters.project >> --prod
      - unless:
          condition: << parameters.skip-tests >>
          steps:
            - common/chrome-upgrade
            - run:
                name: Running unit tests
                command: npm run test -- << parameters.project >> --watch false
            - unless:
                condition: << parameters.skip-e2e >>
                steps:
                  - run:
                      name: Running e2e tests
                      command: npm run e2e
            - store_test_results:
                path: test-results
  build:
    parameters:
      project:
        type: string
    executor: common/node
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Building
          command: npm run build -- << parameters.project >>
      - persist_to_workspace:
          root: .
          paths:
            - dist
  publish-npm:
    parameters:
      path:
        type: string
      access:
        type: enum
        default: 'public'
        enum: [ 'public', 'restricted' ]
    executor: common/node
    steps:
      - attach_workspace:
          at: .
      - common/custom-npm-login
      - run:
          name: Publishing NPM package
          command: cd << parameters.path >> && npm publish --access=<< parameters.access >>
  publish-bitbucket:
    parameters:
      path:
        type: string
      repo:
        type: string
      ssh-permission-fingerprint:
        type: string
        default: ''
    executor: common/node
    steps:
      - add_ssh_keys:
          fingerprints:
            - "<< parameters.ssh-permission-fingerprint >>"
      - attach_workspace:
          at: .
      - run:
          name: Publish NPM package at Bitbcuket
          command: |
            mkdir -p ~/.ssh/ && echo -e "Host bitbucket.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            git config --global user.email "dummy@mail.com"
            git config --global user.name "$CIRCLE_USERNAME"
            git clone --quiet git@bitbucket.org:<< parameters.repo >>-dist.git npmdist
            cd npmdist
            rm -rf *
            cp -R ../<< parameters.path >>/* .
            git add --all
            git commit -m "Bumped version $CIRCLE_TAG"
            git tag $CIRCLE_TAG
            git push && git push --tags
