version: 2.1

description: |
  Build and publish hybrid Apps for iOS / Android
  Repository: https://github.com/okode/orbs

orbs:
  common: okode/common@1.0.224
  android: circleci/android@2
  gradle: circleci/gradle@2
  node: circleci/node@5

jobs:
  ios:
    parameters:
      node-version:
        type: string
        default: '18'
      cocoapods-version:
        type: string
        default: ''
      fastlane-version:
        type: string
        default: ''
      xcode-version:
        type: string
        default: '14.3.1'
      ssh-permission-fingerprint:
        type: string
        default: ''
      custom-npm-login:
        type: boolean
        default: false
      pwa-path:
        type: string
        default: 'www'
    executor:
      name: common/node-mac-machine
      xcode-version: << parameters.xcode-version >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - when:
          condition: << parameters.ssh-permission-fingerprint >>
          steps:
            - add_ssh_keys:
                fingerprints:
                  - '<< parameters.ssh-permission-fingerprint >>'
      - when:
          condition: << parameters.node-version >>
          steps:
            - node/install:
                node-version: << parameters.node-version >>
      - when:
          condition: << parameters.custom-npm-login >>
          steps:
            - common/custom-npm-login
      - node/install-packages:
          cache-version: v3-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
      - install-ios:
          cocoapods-version: << parameters.cocoapods-version >>
          fastlane-version: << parameters.fastlane-version >>
      - run:
          name: Syncing Capacitor project
          command: npx cap sync ios
      - run:
          name: Building
          command: |
            if [[ $CIRCLE_TAG = *-dist ]]; then
              export BUILD_TYPE=release
              export MATCH_PASSWORD=$MATCH_PASSWORD_DIST
            else
              export BUILD_TYPE=beta
            fi
            bundle install && bundle exec fastlane ${CIRCLE_JOB} ${BUILD_TYPE} distribute:true
          no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - artifacts/*.ipa
      - common/notify
  android:
    parameters:
      node-version:
        type: string
        default: '18'
      key-name:
        type: string
        default: android-release.keystore
      dist-certs-repo-url:
        type: string
        default: ''
      ssh-permission-fingerprint:
        type: string
        default: ''
      custom-npm-login:
        type: boolean
        default: false
      pwa-path:
        type: string
        default: 'www'
      android-docker-tag:
        type: string
        default: '2023.08.1-node'
      build-tools-version:
        type: string
        default: ''
      resource-class:
        type: string
        default: medium
    resource_class: << parameters.resource-class >>
    executor:
      name: android/android-docker
      tag: << parameters.android-docker-tag >>
    steps:
      - checkout
      - attach_workspace:
          at: .
      - when:
          condition: << parameters.build-tools-version >>
          steps:
            - run:
                name: Installing required Android Build Tools version
                command: |
                  BUILD_TOOLS_VERSION=$(sdkmanager --list_installed | grep -e "build-tools" | grep -Po "(?<=\|).*?(?=\|)" | head -n 1 | xargs)
                  sdkmanager --uninstall "build-tools;$BUILD_TOOLS_VERSION"
                  sdkmanager --install "build-tools;<< parameters.build-tools-version >>"
      - run:
          name: Fix Android build-tools installation
          shell: /bin/bash
          command: |
            if [ -z "<< parameters.build-tools-version >>" ]; then
              BUILD_TOOLS_VERSION=$(sdkmanager --list_installed | grep -e "build-tools" | grep -Po "(?<=\|).*?(?=\|)" | head -n 1 | xargs)
              BUILD_TOOLS_VERSION=$(echo "$BUILD_TOOLS_VERSION" | tr ' ' '-')
            else
              BUILD_TOOLS_VERSION=<< parameters.build-tools-version >>
            fi
            cp /home/circleci/android-sdk/build-tools/$BUILD_TOOLS_VERSION/d8 /home/circleci/android-sdk/build-tools/$BUILD_TOOLS_VERSION/dx
            cp /home/circleci/android-sdk/build-tools/$BUILD_TOOLS_VERSION/lib/d8.jar /home/circleci/android-sdk/build-tools/$BUILD_TOOLS_VERSION/lib/dx.jar
      - run:
          name: Fix Ruby Gems permissions
          command: sudo chown -R $(whoami) /var/lib/gems && sudo chown -R $(whoami) /usr/local/bin
      - node/install:
          node-version: << parameters.node-version >>
      - when:
          condition: << parameters.custom-npm-login >>
          steps:
            - common/custom-npm-login
      - node/install-packages:
          cache-version: v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Installing Fastlane
          command: sudo gem install fastlane -NV
      - common/keystores:
          dist-certs-repo-url: << parameters.dist-certs-repo-url >>
          ssh-permission-fingerprint: << parameters.ssh-permission-fingerprint >>
          key-name: << parameters.key-name >>
      - run:
          name: Syncing Capacitor project
          command: npx cap sync android
      - gradle/with_cache:
          steps:
            - run:
                name: Building
                command: |
                  if [[ $CIRCLE_TAG = *-dist ]]; then
                    export BUILD_TYPE=release

                    echo "export GOOGLE_APPLICATION_CREDENTIALS=$(mktemp)" >> $BASH_ENV
                    source $BASH_ENV
                    GOOGLE_APPLICATION_CREDENTIALS_JSON=$(echo $GOOGLE_APPLICATION_CREDENTIALS_B64 | base64 --decode)
                    printf '%s\n' "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > $GOOGLE_APPLICATION_CREDENTIALS

                    echo "${GOOGLEPLAY_AUTH_JSON}" > gplay.json
                  else
                    export BUILD_TYPE=beta
                  fi
                  bundle install && bundle exec fastlane ${CIRCLE_JOB} ${BUILD_TYPE} distribute:true
                no_output_timeout: 30m
      - persist_to_workspace:
          root: .
          paths:
            - artifacts/*.apk
            - artifacts/*.aab
      - common/notify

commands:
  install-ios:
    description: Install iOS requirements
    parameters:
      cocoapods-version:
        type: string
        default: ''
      fastlane-version:
        type: string
        default: ''
    steps:
      - when:
          condition:
            and:
              - not:
                  equal: [ 'latest', << parameters.cocoapods-version >> ]
              - not:
                  equal: [ '', << parameters.cocoapods-version >> ]
          steps:
            - run:
                name: Installing Cocoapods version << parameters.cocoapods-version >>
                command: |
                  sudo gem install cocoapods -v << parameters.cocoapods-version >>
      - when:
          condition:
            equal: [ 'latest', << parameters.cocoapods-version >> ]
          steps:
            - run:
                name: Installing Cocoapods latest version
                command: |
                  sudo gem install cocoapods
      - when:
          condition:
            and:
              - not:
                  equal: [ 'latest', << parameters.fastlane-version >> ]
              - not:
                  equal: [ '', << parameters.fastlane-version >> ]
          steps:
            - run:
                name: Installing Fastlane version << parameters.fastlane-version >>
                command: |
                  sudo gem install fastlane -v << parameters.fastlane-version >>
      - when:
          condition:
            equal: [ 'latest', << parameters.fastlane-version >> ]
          steps:
            - run:
                name: Installing Fastlane latest version
                command: |
                  sudo gem install fastlane
